(define (problem cleaning_rooms_pickup_keys_more_rooms)
  (:domain cleaning_rooms_with_keys_and_pickup)
  
  (:objects
    R1 R2 R3 R4 R5 - room
    CleaningBot - robot
    n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - quantity
    Key1 Key2 Key3 - key
    Mop - mop
    Sweeper - sweeper
  )
  
  (:init
    (at-robot CleaningBot R1)
    (dirty R1)
    (dirty R2)
    (dirty R3)
    (dirty R4)
    (dirty R5)
    (to-be-cleaned R1 n6)
    (to-be-cleaned R2 n3)
    (to-be-cleaned R3 n9)
    (to-be-cleaned R4 n5)
    (to-be-cleaned R5 n10)
    (plus1 n1 n2)
    (plus1 n2 n3)
    (plus1 n3 n4)
    (plus1 n4 n5)
    (plus1 n5 n6)
    (plus1 n6 n7)
    (plus1 n7 n8)
    (plus1 n8 n9)
    (plus1 n9 n10)
    (= (distance R1 R1) 0)
    (= (distance R1 R2) 3)
    (= (distance R1 R3) 2)
    (= (distance R1 R4) 4)
    (= (distance R1 R5) 5)
    (= (distance R2 R1) 3)
    (= (distance R2 R2) 0)
    (= (distance R2 R3) 1)
    (= (distance R2 R4) 3)
    (= (distance R2 R5) 4)
    (= (distance R3 R1) 2)
    (= (distance R3 R2) 1)
    (= (distance R3 R3) 0)
    (= (distance R3 R4) 2)
    (= (distance R3 R5) 3)
    (= (distance R4 R1) 4)
    (= (distance R4 R2) 3)
    (= (distance R4 R3) 2)
    (= (distance R4 R4) 0)
    (= (distance R4 R5) 1)
    (= (distance R5 R1) 5)
    (= (distance R5 R2) 4)
    (= (distance R5 R3) 3)
    (= (distance R5 R4) 1)
    (= (distance R5 R5) 0)
    (= (total-cost) 0)
    (= (cost-of n1) 1)
    (= (cost-of n2) 2)
    (= (cost-of n3) 3)
    (= (cost-of n4) 4)
    (= (cost-of n5) 5)
    (= (cost-of n6) 6)
    (= (cost-of n7) 7)
    (= (cost-of n8) 8)
    (= (cost-of n9) 9)
    (= (cost-of n10) 10)
    (locked R2)
    (locked R3)
    (locked R4)
    (at-key Key1 R1)
    (at-key Key2 R3)
    (at-key Key3 R5)
    (key-opens Key2 R2)
    (key-opens Key1 R3)
    (key-opens Key3 R4)
    (at-mop Mop R2)
    (at-sweeper Sweeper R1)
    (has-dust R1)
    (has-dust R2)
    (has-dust R4)
    (has-stains R2)
    (has-stains R3)
    (has-stains R5)
  )
  
  (:goal (and (not (dirty R1)) (not (dirty R2)) (not (dirty R3)) 
              (not (dirty R4)) (not (dirty R5))
              (at-robot CleaningBot R1)))
              
  (:metric minimize (total-cost))
)
