(define (problem cleaning_rooms_with_keys)
  (:domain cleaning_rooms_with_keys_and_pickup)

  (:objects
    R1 R2 R3 - room
    CleaningBot - robot
    n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 - quantity
    Key1 Key2 - key
    Mop - mop
    Sweeper - sweeper
  )

  (:init
    (at-robot CleaningBot R1)
    (dirty R1)
    (dirty R2)
    (dirty R3)
    (to-be-cleaned R1 n6)
    (to-be-cleaned R2 n3)
    (to-be-cleaned R3 n9)
    (plus1 n1 n2)
    (plus1 n2 n3)
    (plus1 n3 n4)
    (plus1 n4 n5)
    (plus1 n5 n6)
    (plus1 n6 n7)
    (plus1 n7 n8)
    (plus1 n8 n9)
    (plus1 n9 n10)
    (= (distance R1 R1) 0)
    (= (distance R1 R2) 3)
    (= (distance R1 R3) 2)
    (= (distance R2 R1) 3)
    (= (distance R2 R2) 0)
    (= (distance R2 R3) 1)
    (= (distance R3 R1) 2)
    (= (distance R3 R2) 1)
    (= (distance R3 R3) 0)
    (= (total-cost) 0)
    (= (cost-of n1) 1)
    (= (cost-of n2) 2)
    (= (cost-of n3) 3)
    (= (cost-of n4) 4)
    (= (cost-of n5) 5)
    (= (cost-of n6) 6)
    (= (cost-of n7) 7)
    (= (cost-of n8) 8)
    (= (cost-of n9) 9)
    (= (cost-of n10) 10)
    (key-opens Key2 R2)
    (key-opens Key1 R3)
    (has-key CleaningBot Key1)
    (has-key CleaningBot Key2)
    (has-mop CleaningBot Mop)
    (has-sweeper CleaningBot Sweeper)
    (has-dust R1)
    (has-dust R2)
    (has-stains R2)
    (has-stains R3)
  )

  (:goal (and (not (dirty R1))
              (not (dirty R2))
              (not (dirty R3))
              (at-robot CleaningBot R1))
  )

  (:metric minimize (total-cost))
)
